export enum ModeActionTypes {
  SET_PLAYER_WEAPON = 'SET_PLAYER_WEAPON',
  SET_BOT_WEAPON = 'SET_BOT_WEAPON',
  NAVIGATE_TO_HOME = 'NAVIGATE_TO_HOME',
  SET_BOT_WEAPON_LOADING = 'SET_BOT_WEAPON_LOADING',
  SET_WINNER = 'SET_WINNER',
  RESET_STATE = 'RESET_STATE',
  SET_BOTS_WEAPON_IN_BOT_MODE = 'SET_BOTS_WEAPON_IN_BOT_MODE',
}
